"""empty message

Revision ID: afdc03980819
Revises: 
Create Date: 2020-01-29 11:24:13.476191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdc03980819'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Task', sa.Column('created_at', sa.String(length=100), nullable=True))
    op.add_column('Task', sa.Column('deleted_at', sa.String(length=100), nullable=True))
    op.add_column('Task', sa.Column('deleted_by', sa.String(length=100), nullable=True))
    op.add_column('Task', sa.Column('modified', sa.String(length=100), nullable=True))
    op.add_column('Task', sa.Column('modified_by', sa.String(length=100), nullable=True))
    op.add_column('Task_status', sa.Column('created_at', sa.String(length=100), nullable=True))
    op.add_column('Task_status', sa.Column('deleted_at', sa.String(length=100), nullable=True))
    op.add_column('Task_status', sa.Column('modified', sa.String(length=100), nullable=True))
    op.add_column('Team', sa.Column('created_at', sa.String(length=100), nullable=True))
    op.add_column('Team', sa.Column('deleted_at', sa.String(length=100), nullable=True))
    op.add_column('Team', sa.Column('modified', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('created_at', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('deleted_at', sa.String(length=100), nullable=True))
    op.add_column('User', sa.Column('modified', sa.String(length=100), nullable=True))
    op.add_column('User_team_mapping', sa.Column('created_at', sa.String(length=100), nullable=True))
    op.add_column('User_team_mapping', sa.Column('deleted_at', sa.String(length=100), nullable=True))
    op.add_column('User_team_mapping', sa.Column('modified', sa.String(length=100), nullable=True))
    op.add_column('assignee_report', sa.Column('created_at', sa.String(length=100), nullable=True))
    op.add_column('assignee_report', sa.Column('deleted_at', sa.String(length=100), nullable=True))
    op.add_column('assignee_report', sa.Column('modified', sa.String(length=100), nullable=True))
    op.add_column('attachments', sa.Column('created_at', sa.String(length=100), nullable=True))
    op.add_column('attachments', sa.Column('deleted_at', sa.String(length=100), nullable=True))
    op.add_column('attachments', sa.Column('modified', sa.String(length=100), nullable=True))
    op.add_column('task_index_mapping', sa.Column('created_at', sa.String(length=100), nullable=True))
    op.add_column('task_index_mapping', sa.Column('deleted_at', sa.String(length=100), nullable=True))
    op.add_column('task_index_mapping', sa.Column('modified', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_index_mapping', 'modified')
    op.drop_column('task_index_mapping', 'deleted_at')
    op.drop_column('task_index_mapping', 'created_at')
    op.drop_column('attachments', 'modified')
    op.drop_column('attachments', 'deleted_at')
    op.drop_column('attachments', 'created_at')
    op.drop_column('assignee_report', 'modified')
    op.drop_column('assignee_report', 'deleted_at')
    op.drop_column('assignee_report', 'created_at')
    op.drop_column('User_team_mapping', 'modified')
    op.drop_column('User_team_mapping', 'deleted_at')
    op.drop_column('User_team_mapping', 'created_at')
    op.drop_column('User', 'modified')
    op.drop_column('User', 'deleted_at')
    op.drop_column('User', 'created_at')
    op.drop_column('Team', 'modified')
    op.drop_column('Team', 'deleted_at')
    op.drop_column('Team', 'created_at')
    op.drop_column('Task_status', 'modified')
    op.drop_column('Task_status', 'deleted_at')
    op.drop_column('Task_status', 'created_at')
    op.drop_column('Task', 'modified_by')
    op.drop_column('Task', 'modified')
    op.drop_column('Task', 'deleted_by')
    op.drop_column('Task', 'deleted_at')
    op.drop_column('Task', 'created_at')
    # ### end Alembic commands ###
